### ISSUE TITLE
[2.0.x] broken build with openssl 1.1 / gcc 6

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1119]
```
builddir/build/BUILD/php-pecl-swoole-2.0.6/NTS/src/protocol/SSL.c: In function 'swSSL_set_dhparam':
/builddir/build/BUILD/php-pecl-swoole-2.0.6/NTS/src/protocol/SSL.c:558:7: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
     dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
       ^~
```

P.S. with some workaround for #1118 , **1.9.x** build is OK, so this is 2.0.x only

**Comment by matyhtf** [comment]
The latest code has been fixed.

**Comment by remicollet** [comment]
Fix confirmed, thanks
