### ISSUE TITLE
PHP 8.0.0 alpha 1 and Swoole 4.5.2 compile error

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#3424]
Hi,
Im trying to compile the latest Swoole (4.5.2 not master) with [PHP 8.0.0 alpha 1](https://downloads.php.net/~pollita/) and the following error occurs:
```
/tmp/swoole/swoole-src-4.5.2/swoole.cc: In function 'void fatal_error(int, const char*, ...)':
/tmp/swoole/swoole-src-4.5.2/swoole.cc:284:125: error: cannot convert 'const char*' to 'zend_string* {aka _zend_string*}' for argument '2' to 'zend_object* zend_throw_error_exception(zend_class_entry*, zend_string*, zend_long, int)'
     exception = zend_throw_error_exception(swoole_error_ce, swoole::cpp_string::vformat(format, args).c_str(), code, E_ERROR);
```

What version of Swoole are you using (show your `php --ri swoole`)?
4.5.2

What is your machine environment used (including version of kernel & php & gcc) ?
gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

Linux 73255aea9c46 4.15.0-91-generic #92-Ubuntu SMP x86_64 GNU/Linux

Running in container (debian stretch)

Of course this is an unsupported version but just wanted to give heads up.

**Comment by twose** [comment]
Thank you for your reminder!
I have been working on PHP8 and I have committed a patch to the master (v4.5.3-alpha), you can find it on https://github.com/swoole/swoole-src/pull/3384/files

**Comment by kenashkov** [comment]
Master compiles! Thank you... I should have tried straight to Master but just thought that since the alpha was just released there werent new fixes commited.

**Comment by eldadfux** [comment]
@twose I just tried to build Swoole with the latest docker release of PHP8 (alpha3) and I get the following error during the build:

```
In file included from /swoole-src/src/os/msg_queue.cc:17:
/swoole-src/include/msg_queue.h:34:52: error: 'key_t' has not been declared
   34 | int swMsgQueue_create(swMsgQueue *q, int blocking, key_t msg_key, int perms);
      |                                                    ^~~~~
make: *** [Makefile:280: src/os/msg_queue.lo] Error 1
```

I tried building with both Swoole master and v4.5.3-alpha and I get the same result. The Dockerfile I'm using is available here:
https://github.com/appwrite/appwrite/blob/7be078b283f8f9a058dd924702f597aede3581b2/Dockerfile

BTW, the same Dockerfile works perfectly well with PHP7.4

**Comment by eldadfux** [comment]
@twose, @matyhtf, I'm still getting an error trying to build on PHP8 alpine (php:8.0.0beta1-cli-alpine) image (` syntax error: unexpected "(" (expecting "fi")`):

```
checking if awk is broken... no
checking enable debug log... no
checking enable trace log... no
checking enable sockets support... yes
checking enable openssl support... no
checking enable http2.0 support... yes
checking swoole support... yes, shared
checking enable mysqlnd support... no
checking dir of openssl... no
checking dir of jemalloc... no
checking enable asan... no
checking whether to enable swoole coverage support... no
checking whether to enable Swoole developer build flags... no
checking if compiling with clang... no
./configure: line 5578: syntax error: unexpected "(" (expecting "fi")
ERROR: Service 'appwrite' failed to build: The command '/bin/sh -c wget -q https://github.com/phpredis/phpredis/archive/$PHP_REDIS_VERSION.tar.gz &&   tar -xf $PHP_REDIS_VERSION.tar.gz &&   cd phpredis-$PHP_REDIS_VERSION &&   phpize &&   ./configure &&   make && make install &&   cd .. &&   git clone https://github.com/swoole/swoole-src.git &&   cd swoole-src &&   git checkout $PHP_SWOOLE_VERSION &&   phpize &&   ./configure --enable-sockets --enable-http2 &&   make && make install &&   cd ..' returned a non-zero code: 2
Eldads-MacBook-Pro-2:appwrite eldadfux$ 
```

This is my Docker file: https://github.com/appwrite/appwrite/blob/php8/Dockerfile (as mentioned before, same Dockerfile works with PHP7.4 latest image)
