### ISSUE TITLE
Broken build with OpenSSL 1.1

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1118]
In configure.log

```
configure:4636: checking for SSL_library_init in -lssl
configure:4661: cc -o conftest -Wall -pthread -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lpthread conftest.c -lssl   >&5
/tmp/cctGidyl.o: In function `main':
/builddir/build/BUILD/php-pecl-swoole-1.9.6/NTS/conftest.c:27: undefined reference to `SSL_library_init'
collect2: error: ld returned 1 exit status
```

In OpenSSL >= 1.1, this is not a symbol, but a macro

```
# define SSL_library_init() OPENSSL_init_ssl(0, NULL)
```

BTW, why not simply user the **PHP_SETUP_OPENSSL** which is far better, and rely on **pkgconfig** ?

More 

            PHP_ADD_LIBRARY_WITH_PATH(ssl, "${PHP_OPENSSL_DIR}/lib")

should be 

            PHP_ADD_LIBRARY_WITH_PATH(ssl, "${PHP_OPENSSL_DIR}/$PHP_LIBDIR")

As this can be **lib64** of something else, according to distribution.
