### ISSUE TITLE
build with php8.1 in alpine error

### ISSUE THREAD

**Issue by suconghou** [swoole/swoole-src#4512]
swoole 4.8.2 build with php8.0 is ok , but 8.1 failed

`dockerfile`
```
FROM alpine AS build
RUN apk add --update gcc g++ make cmake wget file xz bison autoconf pcre-dev zlib-dev zlib-static libjpeg-turbo-dev libjpeg-turbo-static libpng-static libpng-dev bzip2-dev bzip2-static openssl-dev openssl-libs-static sqlite-dev sqlite-static oniguruma-dev libsodium-dev libsodium-static c-ares-dev c-ares-static linux-headers
RUN LIBXML2_VERSION=libxml2-2.9.12 && wget http://xmlsoft.org/sources/${LIBXML2_VERSION}.tar.gz && tar zxf ${LIBXML2_VERSION}.tar.gz && cd ${LIBXML2_VERSION} && ./configure && make -j4 && make install
RUN LIBXSLT_VERSION=libxslt-1.1.34 && wget http://xmlsoft.org/sources/${LIBXSLT_VERSION}.tar.gz && tar zxf ${LIBXSLT_VERSION}.tar.gz && cd ${LIBXSLT_VERSION} && ./configure && make -j4 && make install
RUN CURL_VERSION=curl-7.80.0 && wget --no-check-certificate https://curl.haxx.se/download/${CURL_VERSION}.tar.xz && tar Jxf ${CURL_VERSION}.tar.xz && cd ${CURL_VERSION} && ./configure --with-openssl --enable-ares && make -j4 && make install
RUN LIBFREETYPE_VERSION=freetype-2.11.0 && wget --no-check-certificate https://download-mirror.savannah.gnu.org/releases/freetype/${LIBFREETYPE_VERSION}.tar.gz && tar zxf ${LIBFREETYPE_VERSION}.tar.gz && cd ${LIBFREETYPE_VERSION} && ./configure && make -j4 && make install && ln -s $(pwd)/builds/unix/freetype-config /usr/local/bin/freetype-config
RUN LIBZIP_VERSION=libzip-1.8.0 && wget --no-check-certificate https://libzip.org/download/${LIBZIP_VERSION}.tar.xz && tar Jxf ${LIBZIP_VERSION}.tar.xz && cd ${LIBZIP_VERSION} && mkdir build && cd build && cmake .. -DBUILD_SHARED_LIBS=OFF && make -j4 && make install
RUN IMAGEMAGICK_VERSION=7.1.0-16 && wget -O- https://github.com/ImageMagick/ImageMagick/archive/${IMAGEMAGICK_VERSION}.tar.gz | tar xz && cd ImageMagick-${IMAGEMAGICK_VERSION} && ./configure --without-threads --without-fftw --without-perl --disable-opencl --without-modules --without-zip && make -j8 && make install
RUN PHP_VERSION=php-8.1.0 && wget https://www.php.net/distributions/${PHP_VERSION}.tar.xz && tar xJf ${PHP_VERSION}.tar.xz && cd ${PHP_VERSION}
RUN REDIS_VERSION=redis-5.3.4 && cd php-8.*.* && wget https://pecl.php.net/get/${REDIS_VERSION}.tgz && tar zxf ${REDIS_VERSION}.tgz && mv ${REDIS_VERSION} ext/php-redis
RUN MSGPACK_VERSION=msgpack-2.1.2 && cd php-8.*.* && wget https://pecl.php.net/get/${MSGPACK_VERSION}.tgz && tar zxf ${MSGPACK_VERSION}.tgz && mv ${MSGPACK_VERSION} ext/msgpack
RUN IGBINARY_VERSION=igbinary-3.2.6 && cd php-8.*.* && wget https://pecl.php.net/get/${IGBINARY_VERSION}.tgz && tar zxf ${IGBINARY_VERSION}.tgz && mv ${IGBINARY_VERSION} ext/igbinary
RUN IMAGICK_VERSION=imagick-3.6.0 && cd php-8.*.* && wget https://pecl.php.net/get/${IMAGICK_VERSION}.tgz && tar zxf ${IMAGICK_VERSION}.tgz && mv ${IMAGICK_VERSION} ext/imagick
RUN APCU_VERSION=apcu-5.1.21 && cd php-8.*.* && wget https://pecl.php.net/get/${APCU_VERSION}.tgz && tar zxf ${APCU_VERSION}.tgz && mv ${APCU_VERSION} ext/apcu
RUN SWOOLE_VERSION=swoole-4.8.2 && cd php-8.*.* && wget https://pecl.php.net/get/${SWOOLE_VERSION}.tgz && tar zxf ${SWOOLE_VERSION}.tgz && mv ${SWOOLE_VERSION} ext/swoole && \
sed -ie 's/swoole_clock_gettime(CLOCK_REALTIME/clock_gettime(CLOCK_REALTIME/g' "ext/swoole/include/swoole.h"
RUN cd php-8.*.* && rm -rf configure && ./buildconf --force && \
export CFLAGS="-Os" && LDFLAGS="-static" LIBS="$(curl-config --static-libs)" && \
export LIBZIP_LIBS="-L/usr/local/lib64 -lzip" && \
export LIBZIP_CFLAGS=-I/usr/local/include && \
./configure --enable-inline-optimization --enable-static=yes --enable-shared=no --prefix=/usr/local --with-config-file-path=/etc --without-pear --disable-cgi --disable-opcache --disable-fpm --disable-phpdbg --enable-igbinary --with-msgpack --enable-redis --enable-redis-igbinary --enable-apcu --enable-pcntl --enable-sockets --enable-ftp --enable-bcmath --with-zip --with-zlib --enable-mbstring --with-imagick --enable-gd --with-freetype --with-jpeg --with-mysqli --with-pdo-mysql --enable-mysqlnd --with-openssl --enable-openssl --with-openssl-dir=/usr/ --enable-exif --enable-calendar --with-bz2 --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-xsl --with-sodium --with-curl=/usr/local/ --enable-cares && \
sed -i "s{-export-dynamic{-all-static{" Makefile && make -j4 && make install
RUN cd php-8.*.* && \
strip -s /usr/local/bin/php && mv php.ini-production /etc/php.ini && \
sed -i '/^expose_php.*/cexpose_php = Off' /etc/php.ini && sed -i '/^session.serialize_handler.*/csession.serialize_handler = igbinary' /etc/php.ini

FROM alpine
COPY --from=build /usr/local/bin/php /usr/local/bin/php
COPY --from=build /etc/php.ini /etc/php.ini
EXPOSE 9000


```

got error
```

  /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: Zend/asm/make_x86_64_sysv_elf_gas.o: in function `make_fcontext':

  make_x86_64_sysv_elf_gas.S:(.text+0x0): multiple definition of `make_fcontext'; ext/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.o:(.text+0x0): first defined here

  /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: Zend/asm/jump_x86_64_sysv_elf_gas.o: in function `jump_fcontext':

  jump_x86_64_sysv_elf_gas.S:(.text+0x0): multiple definition of `jump_fcontext'; ext/swoole/thirdparty/boost/asm/jump_x86_64_sysv_elf_gas.o:(.text+0x0): first defined here
```

**Comment by deminy** [comment]
Existing releases of Swoole 4.8.x probably don't work well with PHP 8.1 since they were out before PHP 8.1 was officially released. If you want to use Swoole with PHP 8.1, please install Swoole using the source code from the master branch, just like how [the nightly images](https://github.com/swoole/docker-swoole/blob/master/dockerfiles/latest/php8.1/alpine/Dockerfile) are built.

The team is working on having new releases out to better support PHP 8.1. Thanks

**Comment by zip-fa** [comment]
install-swoole.sh

```
#!/usr/bin/env sh

set -ex

if [[ ! -z ${1} ]] ; then
    SWOOLE_VERSION=$1
    shift 1 # Remove Swoole version # out from command line arguments.
else
    SWOOLE_VERSION=master
fi
export SWOOLE_VERSION=$SWOOLE_VERSION

mkdir -p /build
cd /build
git clone -b ${SWOOLE_VERSION} https://github.com/swoole/swoole-src.git
cd swoole-src
phpize
./configure --with-php-config=/usr/local/bin/php-config \
    --enable-http2 \
    --enable-mysqlnd \
    --enable-openssl \
    --enable-sockets \
    --enable-swoole-curl \
    --enable-swoole-json

make && make install
cd && rm -rf /build

echo -e "extension=swoole\nswoole.use_shortname='Off'" > /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
```

COPY ./docker/php/scripts/ /usr/local/bin
chmod +x /usr/local/bin/install-swoole.sh && \
    install-swoole.sh

**Comment by deminy** [comment]
@zip-fa I'm not sure where you get the script `install-swoole.sh`; it's different from what is used in the official image ([ref](https://github.com/swoole/docker-swoole/blob/master/rootfilesystem/usr/local/bin/install-swoole.sh)).

In the official image, we use `curl` instead of `git` to download Swoole. Git is installed only in the dev images (for debugging purposes).

**Comment by zip-fa** [comment]
Your approach is much cleaner, will fix it for myself. Not sure where did i get it, probably from old source
