### ISSUE TITLE
[6.0.0RC1] build failure

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#5577]
```
libtool: compile:  g++ -I. "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/NTS/include" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/NTS/main" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1" -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/include" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/ext-src" "-I/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/thirdparty" -DHAVE_CONFIG_H -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -I/usr/include/php/ext -I/usr/include -DPDO_ODBC_TYPE=\"unixodbc\" -DENABLE_PHP_SWOOLE -DZEND_COMPILE_DL_EXT=1 -c "/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc" -MMD -MF src/coroutine/iouring.dep -MT src/coroutine/iouring.lo  -fPIC -DPIC -o src/coroutine/.libs/iouring.o
/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc:36:31: error: 'IORING_OP_FUTEX_WAIT' was not declared in this scope; did you mean 'IORING_OP_FSETXATTR'?
   36 |     SW_IORING_OP_FUTEX_WAIT = IORING_OP_FUTEX_WAIT,
      |                               ^~~~~~~~~~~~~~~~~~~~
      |                               IORING_OP_FSETXATTR
/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc:37:31: error: 'IORING_OP_FUTEX_WAKE' was not declared in this scope; did you mean 'SW_IORING_OP_FUTEX_WAIT'?
   37 |     SW_IORING_OP_FUTEX_WAKE = IORING_OP_FUTEX_WAKE,
      |                               ^~~~~~~~~~~~~~~~~~~~
      |                               SW_IORING_OP_FUTEX_WAIT
/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc: In member function 'bool swoole::Iouring::dispatch(swoole::IouringEvent*)':
/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc:355:14: error: 'struct io_uring_sqe' has no member named 'futex_flags'
  355 |         sqe->futex_flags = 0;
      |              ^~~~~~~~~~~
/dev/shm/BUILD/php-pecl-swoole6-6.0.0~RC1/swoole-6.0.0RC1/src/coroutine/iouring.cc:364:14: error: 'struct io_uring_sqe' has no member named 'futex_flags'
  364 |         sqe->futex_flags = 0;
      |              ^~~~~~~~~~~
make[1]: *** [Makefile:387: src/coroutine/iouring.lo] Error 1

```

**Comment by remicollet** [comment]
Failure with liburing **2.5** (Fedora 39)
Build OK with version **2.6** (Fedora 41)

Notice: **RHEL-9** and **RHEL-10.0-beta h**ave version 2.5

**Comment by NathanFreeman** [comment]
Thank you for your feedback. Let me see what the issue is.

**Comment by remicollet** [comment]
@NathanFreeman see #5578
