### ISSUE TITLE
Readme claims Swoole 2 works with PHP 5.5+ but actually requires PHP 7

### ISSUE THREAD

**Issue by ryandesign** [swoole/swoole-src#1783]
The Requirements section of the readme states:

> Version-1: PHP 5.3.10 or later
> Version-2: PHP 5.5.0 or later
> Version-4: PHP 7.0.0 or later

However, Swoole 2.1.0 and later fail to compile with PHP 5.

Swoole 2.0.12 still compiles with PHP 5.5, however your [release notes on PECL](https://pecl.php.net/package-info.php?package=swoole&version=2.0.12) state that PHP 5 support was dropped in version 2.0.12.

-----

1. What did you do? If possible, provide a recipe for reproducing the error.

Build Swoole 2.2.0 with PHP 5.5 or 5.6.

2. What did you expect to see?

Successful build

3. What did you see instead?

```
./php_swoole.h:144:2: error: "require PHP version 7.0 or later."
#error "require PHP version 7.0 or later."
 ^
```

4. What version of Swoole are you using (`php --ri swoole`)?

2.2.0

5. What is your machine environment used (including version of kernel & php & gcc) ? 

macOS 10.12.6
Xcode 9.2
Apple LLVM version 9.0.0 (clang-900.0.39.2)
PHP 5.5.38 or 5.6.36

6. If you are using ssl, what is your openssl version?

1.0.2o

**Comment by twose** [comment]
Too many bugs in PHP5, it's too hard to support so we remove it.
See: 
https://github.com/swoole/swoole-src/releases/tag/v2.0.12

**Comment by ryandesign** [comment]
That's fine. You should update the readme to reflect that.

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/commit/a86521fbe15fd3fd24b72461f56ca3cbc9975599

**Comment by ryandesign** [comment]
You've changed the readme to state that swoole 2.x is php7 only, which contradicts previously-published requirements for swoole 2.0.x. So what is the best version of swoole to use with php5? Is it 2.0.12 (the last version that compiles on php5, even though its changelog says php5 support was removed in this version), 2.0.11, or 1.10.5 (the version before 2.x)?
