### ISSUE TITLE
2.0.4: broken build with PHP 5.4

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#990]
Despite paclaje.xml state PHP >= 5.3.10
Perhaps only a matter of fixing this.

Else:
```
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c: In function 'sw_zend_create_execute_data_from_op_array':
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:62: error: 'call_slot' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:62: error: (Each undeclared identifier is reported only once
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:62: error: for each function it appears in.)
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:62: error: 'zend_op_array' has no member named 'nested_calls'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:63: error: 'zend_op_array' has no member named 'used_stack'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:71: warning: implicit declaration of function 'EX_CV_NUM'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:71: warning: passing argument 1 of 'memset' makes pointer from integer without a cast
/usr/include/bits/string3.h:77: note: expected 'void *' but argument is of type 'int'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:73: error: 'zend_execute_data' has no member named 'call_slots'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:73: error: expected expression before ')' token
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:78: warning: implicit declaration of function 'zend_vm_stack_frame_base'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:78: warning: assignment makes pointer from integer without a cast
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:84: error: 'zend_execute_data' has no member named 'call'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:98: warning: cast to pointer from integer of different size
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c: In function 'swoole_corountine_call_function':
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine_util.c:203: warning: implicit declaration of function 'zend_execute_ex'

/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c: In function 'sw_coro_create':
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:71: error: 'call_slot' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:71: error: (Each undeclared identifier is reported only once
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:71: error: for each function it appears in.)
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:71: error: 'zend_op_array' has no member named 'nested_calls'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:72: error: 'zend_op_array' has no member named 'used_stack'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:96: warning: implicit declaration of function 'zend_vm_stack_get_arg_ex'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:96: warning: cast to pointer from integer of different size
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:104: warning: implicit declaration of function 'EX_CV_NUM'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:104: warning: passing argument 1 of 'memset' makes pointer from integer without a cast
/usr/include/bits/string3.h:77: note: expected 'void *' but argument is of type 'int'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:105: error: 'zend_execute_data' has no member named 'call_slots'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:105: error: expected expression before ')' token
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:108: warning: implicit declaration of function 'zend_vm_stack_frame_base'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:108: warning: assignment makes pointer from integer without a cast
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:114: error: 'zend_execute_data' has no member named 'call'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:117: error: 'zend_execute_data' has no member named 'fast_ret'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:160: warning: cast to pointer from integer of different size
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:192: warning: implicit declaration of function 'zend_execute_ex'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c: In function 'sw_coro_resume':
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:407: error: 'zend_execute_data' has no member named 'call'
/builddir/build/BUILD/php-pecl-swoole-2.0.4/NTS/swoole_coroutine.c:408: error: too many arguments to function 'zend_vm_stack_clear_multiple'

```

**Comment by matyhtf** [comment]
The coroutine feature requires version 5.5 or later.

**Comment by remicollet** [comment]
So perhaps, at least, and mess in config.m4

`[ --enable-coroutine Enable coroutine, requires PHP >= 5.5], yes, no)`

**Comment by remicollet** [comment]
And I confirm, build with 5.4.45 and `--disable-coroutine `works

**Comment by matyhtf** [comment]
yeah, I'll update the version requirements in config.m4 and package.xml.

**Comment by matyhtf** [comment]
Fixed. Now, the minimum version requirement is  5.5.
