### ISSUE TITLE
Compiling swoole with redis not working in ubuntu 18.04 for php7.2

### ISSUE THREAD

**Issue by ardabeyazoglu** [swoole/swoole-src#2033]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I clone the source code with `git clone`, run the following commands:

`phpize`
`./configure  --with-php-config=/usr/bin/php-config --enable-debug-log=no --enable-sockets=yes --enable-openssl=yes --enable-http2=yes --enable-async-redis=yes --enable-mysqlnd=yes --enable-coroutine-postgresql=no`
`make`

2. What did you expect to see?
Compiled swoole extension...

3. What did you see instead?
Configure works ok, however make fails because of following error:
`swoole-src/swoole_redis.c:20:10: fatal error: hiredis/hiredis.h: No such file or directory`

Then i downloaded hiredis source into the working directory and run make again. This time it failed like this:
```
/usr/bin/x86_64-linux-gnu-ld: cannot find -lhiredis
collect2: error: ld returned 1 exit status
Makefile:425: recipe for target 'swoole.la' failed
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.1

5. What is your machine environment used (including version of kernel & php & gcc) ?
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Kernel: 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Php: 7.2.10-0ubuntu0.18.04.1
Gcc: (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by twose** [comment]
you must install hiredis: https://github.com/redis/hiredis

**Comment by flddr** [comment]
@ardabeyazoglu `sudo apt install libhiredis-dev`
