### ISSUE TITLE
build on mac 10.11.3 EI Capitan with openssl

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#504]
I have installed openssl and mcrypt with brew , but when build swoole with --enable-openssl, errors bellow:

In file included from ./php_swoole.h:41:
/Users/lushuncheng/swoole-src/include/swoole.h:339:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>

and 

clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lcrypt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole.la] Error 1

solution for error first:

vi Makefile:

append:  -L/usr/local/opt/openssl/lib to LDFLAGS
    -I/usr/local/opt/openssl/include to CPPFLAGS

solution for error second：

vi Makefile:
change -lcrypt to -lmcrypt 

good luck to you!

I think swoole should fit for mcrypt and crypt

**Comment by lscgzwd** [comment]
Thanks, now it fit for mac openssl . 
but also not fit for crypt.

still:
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lcrypt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole.la] Error 1

and clang version:
lushuncheng:~ lushuncheng$ clang -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
