### ISSUE TITLE
[1.9.7] broken build with OpenSSL 1.0.1

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1149]
Build:

```
/builddir/build/BUILD/php-pecl-swoole-1.9.7/NTS/src/network/Client.c: In function 'swClient_enable_ssl_encrypt':
/builddir/build/BUILD/php-pecl-swoole-1.9.7/NTS/src/network/Client.c:180:9: warning: implicit declaration of function 'SSL_CTX_set_alpn_protos' [-Wimplicit-function-declaration]
         if (SSL_CTX_set_alpn_protos(cli->ssl_context, (const unsigned char *) "\x02h2", 3) < 0)
         ^
```

Runtime:

```
+ /usr/bin/php --no-php-ini --define extension=modules/swoole.so --modules
+ grep swoole
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' - modules/swoole.so: undefined symbol: SSL_CTX_set_alpn_protos in Unknown on line 0

```

**Comment by remicollet** [comment]
Notice: this is the version available on RHEL /CentOS 6 and 7

**Comment by remicollet** [comment]
Fix confirmed, thanks

**Comment by remicollet** [comment]
Do you plan a quick 1.9.8 ?  
IMHO both #1149 and #1148 worth it

**Comment by matyhtf** [comment]
OK, Please wait a moment.

**Comment by matyhtf** [comment]
Done.

**Comment by remicollet** [comment]
Thanks, new build should be in my [repo](https://rpms.remirepo.net/) shortly.
