### ISSUE TITLE
PHP 5.5 broken build

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#15]
The --enable-async-mysql don't work with PHP 5.5 (ok with 5.4)

```
 /dev/shm/BUILD/php-pecl-swoole-1.6.7/NTS/swoole.c:376:58: error: 'MYSQLND_NET' has no member named 'stream'
```
