### ISSUE TITLE
error: unknown type name 'clockid_t'; did you mean 'clock_id_t'?

### ISSUE THREAD

**Issue by ryandesign** [swoole/swoole-src#1364]
Helllo, I'm the maintainer of swoole in the MacPorts package management system.

swoole 1.9.21 compiles fine on macOS 10.12 but cannot compile on OS X 10.11 or earlier:

```
In file included from ./php_swoole.h:48:
/path/to/include/swoole.h:83:19: error: unknown type name 'clockid_t'; did you mean 'clock_id_t'?
int clock_gettime(clockid_t which_clock, struct timespec *t);
                  ^~~~~~~~~
                  clock_id_t
/usr/include/mach/clock_types.h:53:13: note: 'clock_id_t' declared here
typedef int     clock_id_t;                     /* clock identification type */
                ^
```

This is a regression from swoole 1.9.20 which compiled fine on OS X 10.7 and later.

**Comment by motecshine** [comment]
try use this commit https://github.com/swoole/swoole-src/pull/1365/commits/c80ad66d0a2af0fa732fa24cfe726556c082f84b,

**Comment by ryandesign** [comment]
Thanks, but then the problem continues with:

```
/path/to/src/core/base.c:1026:19: error: unknown type name 'clockid_t'; did you mean 'clock_id_t'?
int clock_gettime(clockid_t which_clock, struct timespec *t)
                  ^~~~~~~~~
                  clock_id_t
/usr/include/mach/clock_types.h:53:13: note: 'clock_id_t' declared here
typedef int     clock_id_t;                     /* clock identification type */
                ^
```

But it looks like that's the only other place in the code that `clockid_t` is used.

**Comment by zuozhehao** [comment]
@ryandesign
https://github.com/swoole/swoole-src/commit/3460b851c1fd12d800bf2dec705fb8f0851e15b2

**Comment by motecshine** [comment]
@ryandesign  Yes, you are right,  fix in https://github.com/swoole/swoole-src/pull/1365/files

**Comment by ryandesign** [comment]
> @ryandesign Yes, you are right, fix in https://github.com/swoole/swoole-src/pull/1365/files

Thanks, with that change I can confirm it now builds on OS X 10.7 and later again.
